# This is a "normal" job.
universe = vanilla

# Files to place stdout and stderr
output = output/process_$(Cluster)_$(Process).out
error = error/process_$(Cluster)_$(Process).err
log = log/process_$(Cluster)_$(Process).log
#+IsBuildJob = true
#requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") && (IsBuildSlot == true)
requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") 

# Copy environment variables from the submit node
getenv = True
environment = "PATH=/bin:/usr/bin:/usr/local/bin LD_LIBRARY_PATH= PYTHONPATH="

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate the executable to be run and any other input files needed
executable = /home/mouginot/htc_script/cvt.bash 
transfer_input_files = /home/mouginot/htc_script/cvt.bash, /home/mouginot/htc_script/std_setup.bash, /home/mouginot/htc_script/load.bash, /home/mouginot/cyXX.tar.gz, input.xml

# Command line arguments for the executable
arguments = $(file)

# Don't send emails
notification = never

# Request resources
request_cpus = 1
request_memory = 20GB
request_disk = 20GB

queue file from input.txt 
